name: Build and deploy to new infra - hs-webapp-private-db

on:
  push:
    branches:
      - starter-no-infra
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build project
        run: dotnet build --configuration Release

      - name: Install dotnet-ef
        run: dotnet tool install -g dotnet-ef --version 8.*

      - name: Publish project
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Create EF Core migrations bundle
        run: dotnet ef migrations bundle --runtime linux-x64 -o ${{env.DOTNET_ROOT}}/myapp/migrationsbundle

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-migration-bundle
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-migration-bundle

      - name: Login to Azure using OIDC and UAMI
        uses: azure/login@v2
        with:
          client-id: 2a7ffb0d-01cd-418f-954a-f9116fb0c6b9
          tenant-id: 5750da6a-1c1f-48a6-bd93-148a77872e28
          subscription-id: 9b5220ee-29d0-4030-ae3b-7aae1a4296e6

      - name: Deploy to new Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hs-webapp-private-db'
          slot-name: 'Production'
          package: .
