# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - msdocs-core-sql-webapp

on:
  push:
    branches:
      - starter-no-infra
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Install dotnet-ef
        run: dotnet tool install -g dotnet-ef --version 8.*

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Create EF Core migrations bundle
        run: dotnet ef migrations bundle --runtime linux-x64 -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-migration-bundle
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-migration-bundle
          path: ./myapp
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 2a7ffb0d-01cd-418f-954a-f9116fb0c6b9
          tenant-id: 5750da6a-1c1f-48a6-bd93-148a77872e28
          subscription-id: 9b5220ee-29d0-4030-ae3b-7aae1a4296e6

      - name: Run migration bundle via SSH
        run: |
          az webapp ssh \
            --resource-group rg-hs-todo \
            --name hs-ms-webapp-private-db \
            --command "chmod +x /home/site/wwwroot/migrationsbundle && /home/site/wwwroot/migrationsbundle -- --environment Production"    
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hs-ms-webapp-private-db'
          slot-name: 'Production'
          package: ./myapp
