name: Build and deploy ASP.Net Core app to Azure Web App - msdocs-core-sql-XYZ

on:
  push:
    branches:
      - starter-no-infra
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef

      - name: Build EF Migrations Bundle
        run: |
          dotnet restore
          dotnet ef migrations bundle --output myapp/migrationsbundle --configuration Release --project src/TodoApp/TodoApp.csproj --startup-project src/TodoApp/TodoApp.csproj

      - name: Publish .NET app
        run: dotnet publish src/TodoApp/TodoApp.csproj -c Release -o myapp

      - name: Create EF Core migrations bundle
        run: dotnet ef migrations bundle --output ${{ env.DOTNET_ROOT }}/myapp/migrations.bundle

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E28C72F46C3E46FDBECC489806502040 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A20EAB20743E4403902158D62800B7D3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B8366EC6061B43388D460C291605CB80 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ms-todo-webapp'
          slot-name: 'Production'
          package: .

